export const uiIcons = {
  close: "",
  stop: "",
  add: "",
  accept: "",
  success: "",
  decline: "",
  error: "",
  pending: "",
  search: "",
  refresh: "󰑓",
  save: "",
  debug: "",
} as const;

export const icons = [
  { font: "", color: "blue", name: "C", match: /\.(c|h)$/ },
  { font: "", color: "blue", name: "C++", match: /\.(cpp|hpp)$/ },
  { font: "󰌛", color: "green", name: "C#", match: /\.cs$/ },
  { font: "", color: "yellow", name: "Javascript", match: /\.js$/ },
  { font: "", color: "lightblue", name: "Typescript", match: /\.ts$/ },
  { font: "", color: "lightblue", name: "React", match: /\.(jsx|tsx)$/ },
  { font: "", color: "purple", name: "PHP", match: /\.php$/ },
  { font: "", color: "lightblue", name: "Perl", match: /\.pl$/ },
  { font: "", color: "yellow", name: "Python", match: /\.py$/ },
  { font: "", color: "lightblue", name: "Go", match: /\.go$/ },
  { font: "", color: "red", name: "Java", match: /\.java$/ },
  { font: "", color: "red", name: "Ruby", match: /\.rb$/ },
  { font: "", color: "lightblue", name: "Lua", match: /\.lua$/ },
  { font: "", color: "orange", name: "HTML", match: /\.html$/ },
  { font: "", color: "lightblue", name: "CSS", match: /\.(css|less)$/ },
  { font: "", color: "pink", name: "Sass", match: /\.(sass|scss)$/ },
  { font: "", color: "green", name: "Vim", match: /\.vim$/ },
  { font: "", color: "green", name: "Script", match: /(\.(sh|fish|zsh)|bashrc|zshrc|fishrc)$/ },
  { font: "", color: "yellow", name: "JSON", match: /\.json$/ },
  { font: "", color: "red", name: "Yaml", match: /\.ya?ml$/ },
  { font: "", color: "gray", name: "Toml", match: /\.toml$/ },
  { font: "", color: "gray", name: "Config", match: /(\.(ini|conf)|Makefile|config)$/ },
  { font: "󰗀", color: "orange", name: "Xml", match: /\.xml$/ },
  { font: "󰆼", color: "yellow", name: "SQL", match: /\.(sql|sqlite)$/ },
  { font: "", color: "lightblue", name: "Markdown", match: /\.(md|markdown)$/ },
  { font: "󰈙", color: "gray", name: "Text", match: /\.txt$/ },
  { font: "", color: "orange", name: "Git", match: /(\.git[\\\/])|(git)([^\\\/])*$/i },
  { font: "", color: "blue", name: "Docker", match: /docker([^\\\/])*$/i },
  { font: "", color: "purple", name: "Image", match: /\.(png|jpg|jpeg|gif|webp|svg)$/ },
  { font: "󰖟", color: "lightblue", name: "WEB", match: /^(https?:\/\/|envim-browser:\/\/)/ },
  { font: "", color: "gray", name: "Terminal", match: /^term:\/\// },
  { font: "", color: "red", name: "Quickfix", match: /\[(Quickfix|Location) List\]/ },
  { font: "󰋗", color: "pink", name: "Help", match: /help$/ },
  { font: "", color: "gray", name: "File", match: /.*/ },
];

export const notificates = [
  { font: "", kinds: ["empty", "echo", "echomsg", "lua_print", "progress", ""]},
  { font: "", kinds: ["quickfix", "search_count", "search_cmd"]},
  { font: "", kinds: ["wmsg", "verbose"]},
  { font: "", kinds: ["emsg", "echoerr", "lua_error", "rpc_error", "shell_err"]},
  { font: "", kinds: ["confirm", "confirm_sub"]},
  { font: "󰌑", kinds: ["return_prompt"]},
  { font: "", kinds: ["mode", "command", "list_cmd", "number_prompt", "shell_out", "shell_ret", "shell_cmd"]},
  { font: "", kinds: ["bufwrite", "wildlist", "completion", "undo"]},
  { font: "", kinds: ["ruler"]},
  { font: "", kinds: ["debug"]},
];
